// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

// app/layout.js
import '../styles/globals.css';
import Header from '../components/Header';
import Footer from '../components/Footer';
import { CssBaseline, Container } from '@mui/material';

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<CssBaseline />
				<Header />
				<Container>{children}</Container>
				<Footer />
			</body>
		</html>
	);
}
